# Generated by Django 6.0.4 on 2026-04-27 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
            ],
            options={
                'db_table': 'tbl_users',
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('date_start', models.TextField(blank=True, null=True)),
                ('hashtag', models.TextField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='sim.user')),
            ],
            options={
                'db_table': 'tbl_expenses',
            },
        ),
    ]
