# Generated by Django 6.0.4 on 2026-04-27 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_calendar_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
